# Generated by Django 6.0.4 on 2026-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0002_alter_karya_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
