# Generated by Django 6.0.4 on 2026-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0003_karya_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('tanggal_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='karya',
            name='kategori',
            field=models.CharField(choices=[('pidana', 'Hukum Pidana'), ('perdata', 'Hukum Perdata'), ('htn', 'Hukum Tata Negara'), ('han', 'Hukum Administrasi Negara')], default='pidana', max_length=20),
        ),
    ]
