# Generated by Django 6.0.4 on 2026-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0004_berita_karya_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='naskah/'),
        ),
    ]
