# Generated by Django 6.0.4 on 2026-04-20 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0005_karya_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('tanggal_tambah', models.DateTimeField(auto_now_add=True)),
                ('karya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentars', to='tulisan.karya')),
            ],
        ),
    ]
