# Generated by Django 6.0.4 on 2026-04-20 05:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0006_komentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='isi',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='karya',
            name='isi',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
