# Generated by Django 6.0.4 on 2026-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0007_alter_berita_isi_alter_karya_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='jurnal_pdf/'),
        ),
        migrations.AddField(
            model_name='karya',
            name='is_jurnal_ilmiah',
            field=models.BooleanField(default=False),
        ),
    ]
