# Generated by Django 6.0.4 on 2026-04-20 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0008_karya_file_pdf_karya_is_jurnal_ilmiah'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='penulis_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_karya', to=settings.AUTH_USER_MODEL),
        ),
    ]
