# Generated by Django 6.0.4 on 2026-04-22 08:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0011_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='karya',
            name='gambar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
