# Generated by Django 6.0.4 on 2026-04-22 09:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0012_alter_berita_gambar_alter_karya_gambar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='file_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
