# Generated by Django 6.0.4 on 2026-04-22 17:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0013_alter_karya_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='karya',
            name='file_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
