# Generated by Django 6.0.4 on 2026-04-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tulisan', '0014_komentar_is_approved_alter_karya_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='kategori',
            field=models.CharField(choices=[('pidana', 'Hukum Pidana'), ('perdata', 'Hukum Perdata'), ('htn', 'Hukum Tata Negara'), ('han', 'Hukum Administrasi Negara'), ('umum', 'Umum'), ('polkum', 'Politik Hukum'), ('politik', 'Politik')], default='pidana', max_length=20),
        ),
    ]
